### ISSUE TITLE
OOB Exception with slab icons. 

### ISSUE THREAD

**Issue by darkhax** [MinecraftModArchive/Dendrology#37]
When using Not Enough Items, [these exceptions](https://gist.github.com/darkhax/dafee465377b36eb946e) are captured. This likely reflects an underlying issue in the code which is only revealed when mods like NEI are installed.

**Comment by ScottKillen** [comment]
Nope. No underlying issue.

1. NEI asked for a subblock that doesn't exist.
2. Ancient Trees properly throws and exception.
3. NEI properly catches and handles the exception.
4. NEI prints the exception stack trace to the log.

Because of this last step (and I don't know why ChickenBones prints the stack trace) some people see the stack trace and think there is some bug...but the truth is that everything is working properly.

This behavior is actually necessary because of other mods that interact badly. See #33 .

I can change the exception so that it is clear it is not a bug when it shows up in the logs and I can also add an NEI handler so that NEI won't ask about the non-existent subblocks...but, in truth, that requires an outside dependency on NEI and I've been struggling against feeling forced to do it only because NEI spams the log with the stack trace.

**Comment by darkhax** [comment]
Generally when people have blocks with meta textures, they will provide a default case to prevent this exception to prevent a crash if something is to mess up. I generally return blocks.fire.getIcon(0, 0); so that players know this block is bugged out at can deal with it correctly. 

As for NEI, it will normally only show you the blocks which you have told it to show, which is why I had thought it was an underlying issue in your code. From what I have seen, NEI will only show meta value 0 unless a getSubBlocks/getSubItems method is overridden. In your case, none of your blocks override this themselves, however in your core your slab item extends the base slab item which in turn extends ItemBlock. Within the item block code they use 
```java
this.block.getSubBlocks(itemIn, tab, subItems);
```
which in turn is inherited by your code. Given how slabs actually handle their meta data, and the restrictions it has imposed, I believe that this may actually be related to a much larger issue that just hasn't presented itself. I have created a fair amount of slab blocks and haven't encountered this issue before, which is why I am a bit nervous to see it here.

**Comment by ScottKillen** [comment]
Again, this is not a crash, nor some hidden flaw that should cause anxiety.
This is a design choice that I made. The only reason this is an issue is
because ChockenBones made a design choice to dump a handled and disarmed
exception to the log.

**Comment by ScottKillen** [comment]
At any rate reworked in the latest version to quell nerves. :grinning:
